import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App', description: 'Generated by create next app',
}

export default function RootLayout ({ children }) {
  return (<html lang="en">
  <body className="flex min-h-screen flex-col">
  <nav className="sticky top-0 left-0 mx-auto w-full border-b px-4 sm:px-10">
    <Navbar/>
  </nav>
  <div className="flex-grow px-4 sm:px-10">
    {children}
  </div>
  <footer className="mt-auto bg-gray-200">
    {/* Your footer content goes here */}
  </footer>
  </body>
  </html>)
}
